version: "3.7"

services:
    contact:
      networks:
        internal:
          aliases:
            - contact
        dmz:
          aliases:
            - contact
      env_file:
        - ./environment

networks:
    dmz:
        name: dmz
        external: true
    internal:
        name: internal
